# Generated by Django 5.1 on 2024-09-29 18:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_de_credit',
            fields=[
                ('card_number', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('card_name', models.CharField(max_length=255)),
                ('user_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('expiration', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=255)),
                ('article_img', models.ImageField(upload_to='user_article/')),
                ('article_content', models.TextField()),
                ('article_type', models.TextField()),
                ('article_created', models.DateTimeField(auto_now_add=True)),
                ('article_updated', models.DateTimeField(auto_now=True)),
                ('article_disp', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('article_price', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('user_delete', models.BooleanField(default=False)),
                ('article_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('id_article', models.JSONField(default=list)),
                ('id_transaction', models.TextField()),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut1', models.BooleanField(blank=True, default=False)),
                ('statut2', models.BooleanField(blank=True, default=False)),
                ('destination', models.TextField(blank=True)),
                ('id_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sujet', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('destinataire', models.CharField(max_length=255)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mon_panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panier_article', models.TextField(blank=True, null=True)),
                ('panier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_env', models.TextField()),
                ('user_rec', models.TextField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('Cart_de_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eboutique.cart_de_credit')),
            ],
        ),
        migrations.CreateModel(
            name='user_profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profil', models.ImageField(blank=True, null=True, upload_to='user_profil/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
